/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/3EGO7zEBKib
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent, CardDescription, CardFooter } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function Landing() {
  const [isScrolledDown, setIsScrolledDown] = useState(false)
  useEffect(() => {
    const handleScroll = () => {
      const scrollY = window.pageYOffset
      setIsScrolledDown(scrollY > 0)
    }
    window.addEventListener("scroll", handleScroll)
    return () => window.removeEventListener("scroll", handleScroll)
  }, [])
  const [isNavOpen, setIsNavOpen] = useState(false)
  return (
    <div className="min-h-screen bg-gray-100">
      <header
        className={`bg-blue-600 text-white p-4 flex justify-between items-center fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
          isScrolledDown ? "-translate-y-full opacity-0 pointer-events-none" : "translate-y-0 opacity-100"
        }`}
      >
        <div className="flex items-center space-x-2">
          <WavesIcon className="h-8 w-8" />
          <span className="text-2xl font-bold">BlueWave Analytics</span>
        </div>
        <nav className="space-x-4 hidden md:flex">
          <a href="#" className="hover:underline">
            Home
          </a>
          <a href="#" className="hover:underline">
            Features
          </a>
          <a href="#" className="hover:underline">
            Contact
          </a>
          <Button variant="outline" className="bg-white text-blue-600">
            Get Started
          </Button>
        </nav>
        <button className="md:hidden" onClick={() => setIsNavOpen(!isNavOpen)}>
          <MenuIcon className="h-6 w-6" />
        </button>
      </header>
      <div
        className={`fixed top-0 left-0 w-full h-full bg-gray-800 text-white z-40 transition-all duration-300 ${
          isNavOpen ? "opacity-100 pointer-events-auto" : "opacity-0 pointer-events-none"
        }`}
      >
        <div className="flex flex-col items-center justify-center h-full space-y-6">
          <a href="#" className="text-2xl font-bold hover:underline" onClick={() => setIsNavOpen(false)}>
            Home
          </a>
          <a href="#" className="text-2xl font-bold hover:underline" onClick={() => setIsNavOpen(false)}>
            Features
          </a>
          <a href="#" className="text-2xl font-bold hover:underline" onClick={() => setIsNavOpen(false)}>
            Contact
          </a>
          <Button variant="outline" className="bg-white text-blue-600" onClick={() => setIsNavOpen(false)}>
            Get Started
          </Button>
        </div>
      </div>
      <section className="bg-blue-600 text-white text-center py-20 animate-fade-in">
        <h1 className="text-4xl font-bold">Revolutionizing Water Management</h1>
        <p className="mt-4">Empowering you to monitor and manage water usage efficiently.</p>
        <Button className="mt-6 animate-fade-in-up">Learn More</Button>
      </section>
      <section className="py-20 animate-fade-in">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-10">App Features</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-fade-in-up">
            <Card className="animate-fade-in-up">
              <CardHeader>
                <img src="/placeholder.svg" alt="Real-time Monitoring" className="mx-auto" />
                <CardTitle>Real-time Monitoring</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription>
                  <ul className="list-disc pl-4">
                    <li>Instant updates</li>
                    <li>Data Accuracy</li>
                    <li>Remote Accessibility</li>
                  </ul>
                </CardDescription>
              </CardContent>
            </Card>
            <Card className="animate-fade-in-up">
              <CardHeader>
                <img src="/placeholder.svg" alt="Usage Tracking" className="mx-auto" />
                <CardTitle>Usage Tracking</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription>
                  <ul className="list-disc pl-4">
                    <li>Historical Data</li>
                    <li>Usage Patterns</li>
                    <li>Resource Optimization</li>
                  </ul>
                </CardDescription>
              </CardContent>
            </Card>
            <Card className="animate-fade-in-up">
              <CardHeader>
                <img src="/placeholder.svg" alt="Alerts" className="mx-auto" />
                <CardTitle>Alerts</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription>
                  <ul className="list-disc pl-4">
                    <li>Immediate notifications</li>
                    <li>Customizable Thresholds</li>
                    <li>Preventive measures</li>
                  </ul>
                </CardDescription>
              </CardContent>
            </Card>
            <Card className="animate-fade-in-up">
              <CardHeader>
                <img src="/placeholder.svg" alt="Data Analysis" className="mx-auto" />
                <CardTitle>Data Analysis</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription>
                  <ul className="list-disc pl-4">
                    <li>Comprehensive reports</li>
                    <li>Trend analysis</li>
                    <li>Predictive analytics</li>
                  </ul>
                </CardDescription>
              </CardContent>
            </Card>
            <Card className="animate-fade-in-up">
              <CardHeader>
                <img src="/placeholder.svg" alt="User Management" className="mx-auto" />
                <CardTitle>User Management</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription>
                  <ul className="list-disc pl-4">
                    <li>Role-based access</li>
                    <li>Secure authentication</li>
                    <li>User activity logs</li>
                  </ul>
                </CardDescription>
              </CardContent>
            </Card>
            <Card className="animate-fade-in-up">
              <CardHeader>
                <img src="/placeholder.svg" alt="Mobile App Integration" className="mx-auto" />
                <CardTitle>Mobile App Integration</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription>
                  <ul className="list-disc pl-4">
                    <li>Real-time alerts</li>
                    <li>Remote Monitoring</li>
                    <li>User-friendly interface</li>
                  </ul>
                </CardDescription>
              </CardContent>
            </Card>
            <Card className="animate-fade-in-up">
              <CardHeader>
                <img src="/placeholder.svg" alt="IoT Device Compatibility" className="mx-auto" />
                <CardTitle>IoT Device Compatibility</CardTitle>
              </CardHeader>
              <CardContent>
                <CardDescription>
                  <ul className="list-disc pl-4">
                    <li>Easy integration</li>
                    <li>Wide device support</li>
                    <li>Enhanced data collection</li>
                  </ul>
                </CardDescription>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
      <section className="py-20 bg-gray-200 animate-fade-in">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-10">Contact Us</h2>
          <Card className="max-w-lg mx-auto animate-fade-in-up">
            <CardHeader>
              <CardTitle>Request Our Services</CardTitle>
              <CardDescription>Fill out the form below to get in touch with us.</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-4">
                <div className="space-y-2">
                  <Label htmlFor="name">Name</Label>
                  <Input id="name" placeholder="Enter your name" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="email">Email</Label>
                  <Input id="email" placeholder="Enter your email" type="email" />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="message">Message</Label>
                  <Textarea id="message" placeholder="Enter your message" className="min-h-[100px]" />
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="ml-auto animate-fade-in-up">Send Message</Button>
            </CardFooter>
          </Card>
        </div>
      </section>
      <footer className="bg-gray-800 text-white text-center py-4 animate-fade-in">
        <p>©2024 BlueWaveAnalytics All Rights Reserved</p>
        <div className="space-x-4">
          <a href="#" className="hover:underline">
            Privacy policy
          </a>
          <a href="#" className="hover:underline">
            Terms of Service
          </a>
          <a href="#" className="hover:underline">
            Contact Us
          </a>
        </div>
      </footer>
    </div>
  )
}

function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function WavesIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 6c.6.5 1.2 1 2.5 1C7 7 7 5 9.5 5c2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1" />
      <path d="M2 12c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1" />
      <path d="M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1" />
    </svg>
  )
}
