/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/3EGO7zEBKib
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
"use client";

import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { ContactForm } from "./landing/ContactForm";
import FeatureCard from "./landing/Card";
import { cardData } from "./constants/Constants";
import { ModeToggle } from "./ui/theme-toggler";

export function Landing() {
  const [isScrolledDown, setIsScrolledDown] = useState(false);
  useEffect(() => {
    const handleScroll = () => {
      const scrollY = window.pageYOffset;
      setIsScrolledDown(scrollY > 0);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);
  const [isNavOpen, setIsNavOpen] = useState(false);

  return (
    <div className="min-h-screen bg-slate-100">
      <header
        className={`bg-blue-600 text-white p-4 flex justify-between items-center fixed top-0 left-0 right-0 z-50 transition-all w-full duration-300 ${
          isScrolledDown
            ? "-translate-y-full opacity-0 pointer-events-none"
            : "translate-y-0 opacity-100"
        }`}
      >
        <div className="flex items-center space-x-2">
          {/* <WavesIcon className="h-8 w-8" /> */}
          <span className="text-2xl font-bold">BlueWave Analytics</span>
        </div>
        <nav className="space-x-4 hidden md:flex">
          <a href="#" className="hover:underline underline-offset-4">
            Home
          </a>
          <a href="#" className="hover:underline underline-offset-4">
            Features
          </a>
          <a href="#" className="hover:underline underline-offset-4">
            Contact
          </a>
          <Button variant="outline" className="bg-white text-blue-600">
            Get Started
          </Button>
        </nav>
        <button className="md:hidden" onClick={() => setIsNavOpen(!isNavOpen)}>
          <WavesIcon className="h-6 w-6" />
        </button>
      </header>
      <div
        className={`fixed top-0 left-0 w-full h-full bg-gray-800 text-white z-40 transition-all duration-300 ${
          isNavOpen
            ? "opacity-100 pointer-events-auto"
            : "opacity-0 pointer-events-none"
        }`}
      >
        <div className="flex flex-col items-center justify-center h-full space-y-6">
          <a
            href="#"
            className="text-2xl font-bold hover:underline"
            onClick={() => setIsNavOpen(false)}
          >
            Home
          </a>
          <a
            href="#"
            className="text-2xl font-bold hover:underline"
            onClick={() => setIsNavOpen(false)}
          >
            Features
          </a>
          <a
            href="#"
            className="text-2xl font-bold hover:underline"
            onClick={() => setIsNavOpen(false)}
          >
            Contact
          </a>
          <Button
            variant="outline"
            className="bg-white text-blue-600"
            onClick={() => setIsNavOpen(false)}
          >
            Get Started
          </Button>
        </div>
      </div>
      <section className="bg-blue-600 text-white text-center py-20 animate-fade-in">
        <h1 className="text-4xl font-bold">Revolutionizing Water Management</h1>
        <p className="mt-4 px-4 md:px-48">
          At our startup, we are driven by a collective vision to revolutionize
          water management through innovative technology. Our mission is to
          provide a comprehensive water tracking software platform that empowers
          borehole owners, water suppliers, and individual users to monitor and
          manage water usage efficiently.
        </p>
        <Button className="mt-6 animate-fade-in-up">Learn More</Button>
      </section>
      <section className="py-20 animate-fade-in">
        <div className="container mx-auto px-4">
          <h2 className="text-3xl font-bold text-center mb-10">App Features</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 animate-fade-in-up">
            <FeatureCard cardData={cardData} />
          </div>
        </div>
      </section>
      <section className="py-20 bg-gray-200 animate-fade-in">
        <ContactForm />
      </section>
      <footer className="bg-gray-800 text-white text-center py-4 animate-fade-in flex gap-4 justify-center ">
        <p>©2024 </p>
        <p>BlueWaveAnalytics</p>
        <p>All Rights Reserved</p>
        <div className="space-x-4">
          <a href="#" className="hover:underline">
            Privacy policy
          </a>
          <a href="#" className="hover:underline">
            Terms of Service
          </a>
          <a href="#" className="hover:underline">
            Contact Us
          </a>
        </div>
        {/* <div className="bg-red-500">
          <ModeToggle />
          </div> */}
      </footer>
    </div>
  );
}

interface IconProps extends React.SVGProps<SVGSVGElement> {}

export function MenuIcon(props: IconProps): JSX.Element {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" y1="6" x2="20" y2="6" />
      <line x1="4" y1="12" x2="20" y2="12" />
      <line x1="4" y1="18" x2="20" y2="18" />
    </svg>
  );
}

export function WavesIcon(props: IconProps): JSX.Element {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M2 6c.6.5 1.2 1 2.5 1C7 7 7 5 9.5 5c2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1" />
      <path d="M2 12c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1" />
      <path d="M2 18c.6.5 1.2 1 2.5 1 2.5 0 2.5-2 5-2 2.6 0 2.4 2 5 2 2.5 0 2.5-2 5-2 1.3 0 1.9.5 2.5 1" />
    </svg>
  );
}
